# Site settings
title: Zhanat KAPPASSOV
general_email: hidden
academic_email: my-name@nu.edu.kz

description: > # this means to ignore newlines until "baseurl:"
  Research & Development, Teaching in Robotics, Tactile, Control, Manipulation, Touch, Haptics, Interfaces, Perception; He is originally trained as an engineer in Electrical Engineering, Radiotehnika, Power Electronics.

baseurl: "/" # the subpath of your site, e.g. /blog/

url: "https://zkappassov.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: zkappassov
linkedin_username: hidden
facebook_username: hidden
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
